// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ParcelService.Infrastructure;

#nullable disable

namespace ParcelService.Infrastructure.Migrations
{
    [DbContext(typeof(EFAppContext))]
    partial class EFAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParcelService.Domain.Entities.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Destination", "ParcelService.Domain.Entities.Parcel.Destination#Destination", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Terminal")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Receiver", "ParcelService.Domain.Entities.Parcel.Receiver#PersonInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Address", "ParcelService.Domain.Entities.Parcel.Receiver#PersonInfo.Address#Address", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("HouseNumber")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Sender", "ParcelService.Domain.Entities.Parcel.Sender#PersonInfo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Address", "ParcelService.Domain.Entities.Parcel.Sender#PersonInfo.Address#Address", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("HouseNumber")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasColumnType("text");
                                });
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Tracking", "ParcelService.Domain.Entities.Parcel.Tracking#Tracking", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("TrackingNumber")
                                .HasColumnType("uuid");
                        });

                    b.HasKey("Id");

                    b.ToTable("Parcel", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
