name: Continous Delivery

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      docker-context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      tag:
        required: true
        type: string
      registry:
        required: false
        type: string
        default: ghcr.io
      owner:
        required: false
        type: string
        default: mikkelrlarsen
  
jobs:
  continous_delivery:
    runs-on: ubuntu-latest  
    permissions:
      contents: read
      packages: write     

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ${{ inputs.registry }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.owner }}/${{ inputs.image-name }}:${{ inputs.tag }}
