name: ParcelService Pipeline

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'src/ParcelService/**'
      - '!src/ParcelService/Docs/**' 
jobs:
  Countinous_Integration:
    permissions: 
      contents: read
      checks: write
    uses: ./.github/workflows/ContinousIntegration.yml
      
  Countinous_Delivery:
    needs: Countinous_Integration
    permissions: 
      contents: read
      packages: write
    uses: ./.github/workflows/ContinousDelivery.yml
    with:
      image-name: parcelservice
      docker-context: src
      dockerfile: src/ParcelService/Dockerfile
      tag: ${{ github.sha }}

  Staging:
    needs: Countinous_Delivery
    uses: ./.github/workflows/Staging.yml
    with:
      deployment-name: ParcelDeployment
      container-name: parcelservice
      image-name: parcelservice
      tag: ${{ github.sha }}
      
  Production:
    needs: Staging
    uses: ./.github/workflows/Production.yml
    with:
      deployment-name: ParcelDeployment
      container-name: parcelservice
      image-name: parcelservice
      tag: ${{ github.sha }}

  UpdateDocs:
    needs: Production
    permissions: 
      contents: write
    uses: ./.github/workflows/UpdateK8DeploymentYaml.yml
    with:
      container-name: parcelservice
      filepath: Docs/KubernetesDocuments/Deployments/ParcelService/ParcelDeployment
      tag: ${{ github.sha }}
